server:
   servlet:
      contextPath: /iam/v2
   port: 8000

spring:
   profiles:
      active: dev
---

spring:
   profiles: dev
   datasource:
      url: jdbc:oracle:thin:@prior-db.cmbcolowaua6.ap-southeast-1.rds.amazonaws.com:1922:ORCL
      username: prior_db
      password: P@5sw0rd
      driver-class-oracle:
        jdbc:
        driver: OracleDriver
   jpa:
      database: oracle
      show-sql: false
      properties:
         hibernate:
#            jdbc:
#               time_zone: Asia/Bangkok
            default_schema: prior_db
            temp:
               use_jdbc_metadata_defaults: false


security:
   jwt:
      access:
         secret: jwt-access-secret
         expirationTime: 1800 # second(s)
      refresh:
         secret: jwt-refresh-secret
         expirationTime: 3600 # second(s)




